"""Initial migration - create decisions and votes tables

Revision ID: 60751c4d60fc
Revises: 
Create Date: 2025-11-12 11:23:24.274979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60751c4d60fc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('proposer_phone', sa.String(), nullable=False),
    sa.Column('proposer_name', sa.String(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('group_size_at_creation', sa.Integer(), nullable=False),
    sa.Column('approval_threshold', sa.Integer(), nullable=False),
    sa.Column('approval_count', sa.Integer(), nullable=False),
    sa.Column('rejection_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected', 'expired')", name='check_valid_status'),
    sa.CheckConstraint('approval_count >= 0', name='check_approval_count_positive'),
    sa.CheckConstraint('approval_threshold > 0', name='check_threshold_positive'),
    sa.CheckConstraint('group_size_at_creation > 0', name='check_group_size_positive'),
    sa.CheckConstraint('rejection_count >= 0', name='check_rejection_count_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_channel_id'), 'decisions', ['channel_id'], unique=False)
    op.create_index(op.f('ix_decisions_id'), 'decisions', ['id'], unique=False)
    op.create_index(op.f('ix_decisions_proposer_phone'), 'decisions', ['proposer_phone'], unique=False)
    op.create_table('votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('voter_phone', sa.String(), nullable=False),
    sa.Column('voter_name', sa.String(), nullable=False),
    sa.Column('vote_type', sa.String(), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('voted_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("vote_type IN ('approve', 'reject')", name='check_valid_vote_type'),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('decision_id', 'voter_phone', name='unique_voter_per_decision')
    )
    op.create_index(op.f('ix_votes_decision_id'), 'votes', ['decision_id'], unique=False)
    op.create_index(op.f('ix_votes_id'), 'votes', ['id'], unique=False)
    op.create_index(op.f('ix_votes_voter_phone'), 'votes', ['voter_phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votes_voter_phone'), table_name='votes')
    op.drop_index(op.f('ix_votes_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_decision_id'), table_name='votes')
    op.drop_table('votes')
    op.drop_index(op.f('ix_decisions_proposer_phone'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_channel_id'), table_name='decisions')
    op.drop_table('decisions')
    # ### end Alembic commands ###
