"""add channel_config and config_change_log tables

Revision ID: 88f915c66504
Revises: 8b146b2fa096
Create Date: 2025-11-28 15:59:51.259344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88f915c66504'
down_revision: Union[str, Sequence[str], None] = '8b146b2fa096'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_configs',
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('approval_percentage', sa.Integer(), nullable=False),
    sa.Column('auto_close_hours', sa.Integer(), nullable=False),
    sa.Column('group_size', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.CheckConstraint('approval_percentage > 0 AND approval_percentage <= 100', name='check_valid_percentage'),
    sa.CheckConstraint('auto_close_hours > 0', name='check_valid_hours'),
    sa.CheckConstraint('group_size > 0', name='check_valid_group_size'),
    sa.PrimaryKeyConstraint('channel_id')
    )
    op.create_index(op.f('ix_channel_configs_channel_id'), 'channel_configs', ['channel_id'], unique=False)
    op.create_table('config_change_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('setting_name', sa.String(), nullable=False),
    sa.Column('old_value', sa.Integer(), nullable=False),
    sa.Column('new_value', sa.Integer(), nullable=False),
    sa.Column('changed_by', sa.String(), nullable=False),
    sa.Column('changed_by_name', sa.String(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("setting_name IN ('approval_percentage', 'auto_close_hours', 'group_size')", name='check_valid_setting_name'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_change_logs_channel_id'), 'config_change_logs', ['channel_id'], unique=False)
    op.create_index(op.f('ix_config_change_logs_id'), 'config_change_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_config_change_logs_id'), table_name='config_change_logs')
    op.drop_index(op.f('ix_config_change_logs_channel_id'), table_name='config_change_logs')
    op.drop_table('config_change_logs')
    op.drop_index(op.f('ix_channel_configs_channel_id'), table_name='channel_configs')
    op.drop_table('channel_configs')
    # ### end Alembic commands ###
