from typing import Any, Dict

# Minimal stub for httpx used in the project
def get(url: str, **kwargs: Any) -> Any: ...

def post(url: str, **kwargs: Any) -> Any: ...

class Response:
    status_code: int
    text: str
    def json(self) -> Dict[str, Any]: ...

class AsyncClient:
    async def __aenter__(self) -> "AsyncClient": ...
    async def __aexit__(self, *args: Any) -> None: ...
    async def get(self, url: str, **kwargs: Any) -> Response: ...
    async def post(self, url: str, **kwargs: Any) -> Response: ...
