from typing import Any, Dict, Optional

class Config:
    """Alembic Config object - provides access to .ini file values."""
    config_file_name: Optional[str]
    config_ini_section: str
    
    def get_main_option(self, name: str) -> Optional[str]: ...
    def get_section(self, name: str, default: Dict[str, Any] = ...) -> Dict[str, Any]: ...

# context is both a module and provides context.config property
class context:
    config: Config
    
    @staticmethod
    def configure(**kwargs: Any) -> None: ...
    @staticmethod
    def begin_transaction() -> Any: ...
    @staticmethod
    def run_migrations() -> None: ...
    @staticmethod
    def is_offline_mode() -> bool: ...
    @staticmethod
    def get_x_argument(as_dictionary: bool = False) -> Any: ...

class op:
    @staticmethod
    def create_table(name: str, *args: Any, **kwargs: Any) -> None: ...
    @staticmethod
    def drop_table(name: str) -> None: ...
    @staticmethod
    def add_column(table: str, column: Any) -> None: ...
    @staticmethod
    def drop_column(table: str, column_name: str) -> None: ...
    @staticmethod
    def create_index(name: str, table: str, columns: Any, **kwargs: Any) -> None: ...
    @staticmethod
    def drop_index(name: str, table_name: str = "", **kwargs: Any) -> None: ...
    @staticmethod
    def execute(sql: str) -> None: ...
    @staticmethod
    def get_bind() -> Any: ...
    @staticmethod
    def f(name: str) -> str: ...
