from typing import Any, Dict, List, Optional

class WebClient:
    def __init__(self, token: Optional[str] = None) -> None: ...
    def auth_test(self, **kwargs: Any) -> Dict[str, Any]: ...
    def conversations_members(self, **kwargs: Any) -> Dict[str, Any]: ...
    def conversations_info(self, **kwargs: Any) -> Dict[str, Any]: ...
    def users_info(self, **kwargs: Any) -> Dict[str, Any]: ...
    def reactions_add(self, **kwargs: Any) -> Dict[str, Any]: ...
    def reactions_get(self, **kwargs: Any) -> Dict[str, Any]: ...
    def reactions_remove(self, **kwargs: Any) -> Dict[str, Any]: ...
    def chat_postMessage(self, **kwargs: Any) -> Dict[str, Any]: ...
    def chat_update(self, **kwargs: Any) -> Dict[str, Any]: ...
    def chat_postEphemeral(self, **kwargs: Any) -> Dict[str, Any]: ...
    def oauth_v2_access(self, **kwargs: Any) -> Dict[str, Any]: ...

class SlackApiError(Exception):
    def __init__(self, message: str, response: Optional[Dict[str, Any]] = None) -> None: ...
    response: Optional[Dict[str, Any]]
