# Stub for slack_sdk.web
from typing import Any

class SlackResponse:
    data: dict[str, Any]
    def get(self, key: str, default: Any = None) -> Any: ...
    def __getitem__(self, key: str) -> Any: ...

class WebClient:
    def __init__(self, token: str | None = None, **kwargs: Any) -> None: ...
    def auth_test(self, **kwargs: Any) -> SlackResponse: ...
    def conversations_members(self, *, channel: str, **kwargs: Any) -> SlackResponse: ...
    def conversations_info(self, *, channel: str, **kwargs: Any) -> SlackResponse: ...
    def users_info(self, *, user: str, **kwargs: Any) -> SlackResponse: ...
    def chat_postMessage(self, *, channel: str, text: str | None = None, blocks: Any = None, thread_ts: str | None = None, **kwargs: Any) -> SlackResponse: ...
    def chat_postEphemeral(self, *, channel: str, user: str, text: str | None = None, blocks: Any = None, **kwargs: Any) -> SlackResponse: ...
    def chat_update(self, *, channel: str, ts: str, text: str | None = None, blocks: Any = None, **kwargs: Any) -> SlackResponse: ...
    def oauth_v2_access(self, *, client_id: str, client_secret: str, code: str, redirect_uri: str | None = None, **kwargs: Any) -> SlackResponse: ...

