# Stub for slack_sdk.web
from typing import Any

class WebClient:
    def __init__(self, token: str = ...) -> None: ...
    def auth_test(self) -> dict[str, Any]: ...
    def conversations_members(self, channel: str) -> dict[str, Any]: ...
    def conversations_info(self, channel: str) -> dict[str, Any]: ...
    def users_info(self, user: str) -> dict[str, Any]: ...

