from typing import Any, Iterator

class Session:
    def __enter__(self) -> "Session": ...
    def __exit__(self, exc_type: Any, exc: Any, tb: Any) -> None: ...
    def add(self, obj: Any) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def query(self, *args: Any, **kwargs: Any) -> Any: ...
    def refresh(self, obj: Any) -> None: ...
    def close(self) -> None: ...
    def flush(self) -> None: ...
    def delete(self, obj: Any) -> None: ...
    def execute(self, *args: Any, **kwargs: Any) -> Any: ...

def sessionmaker(*args: Any, **kwargs: Any) -> Any: ...

def declarative_base(*args: Any, **kwargs: Any) -> Any: ...

def relationship(*args: Any, **kwargs: Any) -> Any: ...
